pipeline:
  name: guestbook-deploy
  identifier: guestbookdeploy
  projectIdentifier: jpbartoapplication
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Deploy Guestbook Helm
        identifier: Deploy_Guestbook_Helm
        description: ""
        type: Deployment
        spec:
          deploymentType: NativeHelm
          service:
            serviceRef: org.jpbartoguestbookservice
          environment:
            environmentRef: account.jpbartoawsvpocenv
            deployToAll: false
            infrastructureDefinitions:
              - identifier: jpbartoguestbookinfra
          execution:
            steps:
              - step:
                  name: Helm Deployment
                  identifier: helmDeployment
                  type: HelmDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
            rollbackSteps:
              - step:
                  name: Helm Rollback
                  identifier: helmRollback
                  type: HelmRollback
                  timeout: 10m
                  spec: {}
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
