pipeline:
  name: guestbook-deploy-verb
  identifier: guestbookdeployverb
  tags: {}
  template:
    templateRef: account.jpbartomicroservicedeployverb
    versionLabel: 1.0.0
    templateInputs:
      stages:
        - stage:
            identifier: Deploy_Helm_Chart
            type: Deployment
            spec:
              service:
                serviceRef: org.jpbartoguestbookservice
  projectIdentifier: jpbartoapplication
  orgIdentifier: default
