pipeline:
  name: guestbook-cd
  identifier: guestbookcd
  projectIdentifier: psmjpbarto_guestbook
  orgIdentifier: psmjpbarto
  tags: {}
  stages:
    - stage:
        name: Deploy Terraform
        identifier: Deploy_Terraform
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: Apply Terraform
                  identifier: TerraformApply_1
                  spec:
                    provisionerIdentifier: tmp_provisioner
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            spec:
                              connectorRef: account.jpbartogithubconnector
                              repoName: harness-eval
                              gitFetchType: Branch
                              branch: main
                              folderPath: terraform
                            type: Github
                        providerCredential:
                          type: Aws
                          spec:
                            connectorRef: org.psmjpbarto_cicacheconnector
                            region: us-east-1
                            roleArn: ""
                        environmentVariables:
                          - name: HARNESS_ACCOUNT_ID
                            value: <+account.identifier>
                            type: String
                          - name: HARNESS_PLATFORM_API_KEY
                            value: <+secrets.getValue("harness_platform_api_key")>
                            type: String
                        backendConfig:
                          type: Inline
                          spec:
                            content: |-
                              bucket = "jpbarto-awsvpoc-us-east-1-harness-tf-state"
                              key    = "psm-jpbarto/guestbook/state"
                              region = "us-east-1"
                        varFiles:
                          - varFile:
                              identifier: inline_tfvars
                              type: Inline
                              spec:
                                content: |-
                                  env_name                  = "<+pipeline.variables.EnvironmentRef>"
                                  harness_account_id        = "dLgVufj0RcmqCZSIwllL6g"
                                  harness_org_id            = "<+org.identifier>"
                                  harness_project_id        = "<+project.identifier>"
                                  harness_gitops_agent_id   = "<+pipeline.variables.GitOpsAgentId>"
                                  harness_gitops_cluster_id = "<+pipeline.variables.GitOpsClusterId>"
                                  gitops_target_namespace   = "<+variable.org.squadName>"
                  timeout: 10m
        tags: {}
        delegateSelectors:
          - jpbarto-aws-vpoc-delegate-us-east-1
    - stage:
        name: Sync ArgoCD
        identifier: Sync_ArgoCD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          execution:
            steps:
              - step:
                  type: GitOpsSync
                  name: GitOpsSync_1
                  identifier: GitOpsSync_1
                  spec:
                    prune: false
                    dryRun: false
                    applyOnly: false
                    forceApply: false
                    applicationsList: []
                    retryStrategy: {}
                    retry: false
                    syncOptions:
                      skipSchemaValidation: false
                      autoCreateNamespace: false
                      pruneResourcesAtLast: false
                      applyOutOfSyncOnly: false
                      replaceResources: false
                      prunePropagationPolicy: foreground
                      respectIgnoreDifferences: false
                      serverSideApply: false
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: jpbartoguestbook
          environment:
            environmentRef: account.jpbartoawsvpocenv
            deployToAll: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - jpbarto-aws-vpoc-delegate-us-east-1
  variables:
    - name: EnvironmentRef
      type: String
      description: Harness environment identifier (e.g. us-east-1)
      value: <+input>
    - name: GitOpsAgentId
      type: String
      description: Harness GitOps agent identifier
      value: <+input>
    - name: GitOpsClusterId
      type: String
      description: Harness GitOps cluster identifier
      value: <+input>
