pipeline:
  name: guestbook-cd
  identifier: guestbookcd
  projectIdentifier: psmjpbarto_guestbook
  orgIdentifier: psmjpbarto
  tags: {}
  stages:
    - stage:
        name: Deploy Terraform
        identifier: Deploy_Terraform
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: TerraformApply
                  name: Apply Terraform
                  identifier: TerraformApply_1
                  spec:
                    provisionerIdentifier: tmp_provisioner
                    configuration:
                      type: Inline
                      spec:
                        configFiles:
                          store:
                            spec:
                              connectorRef: account.jpbartogithubconnector
                              repoName: harness-eval
                              gitFetchType: Branch
                              branch: main
                              folderPath: terraform
                            type: Github
                        providerCredential:
                          type: Aws
                          spec:
                            connectorRef: account.jpbartoawsvpocconnector
                            region: us-east-1
                            roleArn: ""
                        backendConfig:
                          type: Remote
                          spec:
                            store:
                              type: S3
                              spec:
                                connectorRef: org.psmjpbarto_cicacheconnector
                                bucketName: jpbarto-awsvpoc-us-east-1-harness-tf-state
                                region: us-east-1
                                paths:
                                  - guestbook/state
                        vars:
                          - name: env_name
                            value: <+pipeline.variables.EnvironmentRef>
                            type: String
                          - name: harness_account_id
                            value: <+account.identifier>
                            type: String
                          - name: harness_org_id
                            value: <+org.identifier>
                            type: String
                          - name: harness_project_id
                            value: <+project.identifier>
                            type: String
                          - name: harness_gitops_agent_id
                            value: <+pipeline.variables.GitOpsAgentId>
                            type: String
                          - name: harness_gitops_cluster_id
                            value: <+pipeline.variables.GitOpsClusterId>
                            type: String
                          - name: harness_gitops_repo_id
                            value: <+pipeline.variables.GitOpsRepoId>
                            type: String
                          - name: gitops_target_namespace
                            value: <+org.variables.squadName>
                            type: String
                        envVars:
                          - name: HARNESS_PLATFORM_API_KEY
                            value: <+secrets.getValue("account.jpbarto-coderio-svc-token")>
                            type: Secret
                  timeout: 10m
        tags: {}
    - stage:
        name: Sync ArgoCD
        identifier: Sync_ArgoCD
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          gitOpsEnabled: true
          execution:
            steps:
              - step:
                  type: GitOpsSync
                  name: GitOpsSync_1
                  identifier: GitOpsSync_1
                  spec:
                    prune: false
                    dryRun: false
                    applyOnly: false
                    forceApply: false
                    applicationsList: []
                    retryStrategy: {}
                    retry: false
                    syncOptions:
                      skipSchemaValidation: false
                      autoCreateNamespace: false
                      pruneResourcesAtLast: false
                      applyOutOfSyncOnly: false
                      replaceResources: false
                      prunePropagationPolicy: foreground
                      respectIgnoreDifferences: false
                      serverSideApply: false
                  timeout: 10m
            rollbackSteps: []
          service:
            serviceRef: jpbartoguestbook
          environment:
            environmentRef: account.jpbartoawsvpocenv
            deployToAll: true
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: EnvironmentRef
      type: String
      description: Harness environment identifier (e.g. us-east-1)
      value: <+input>
    - name: GitOpsAgentId
      type: String
      description: Harness GitOps agent identifier
      value: <+input>
    - name: GitOpsClusterId
      type: String
      description: Harness GitOps cluster identifier
      value: <+input>
    - name: GitOpsRepoId
      type: String
      description: Harness GitOps repository connector identifier
      value: <+input>
