pipeline:
  name: pismo-jpbarto-deploy-pipeline
  identifier: pismojpbartodeploypipeline
  tags: {}
  template:
    templateRef: account.pismojpbartodeploytemplate
    templateInputs:
      stages:
        - insert:
            identifier: Plan
            stages:
              - stage:
                  name: Plan TF Deploy
                  identifier: Plan_TF_Deploy
                  description: ""
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            type: TerraformPlan
                            name: TerraformPlan_1
                            identifier: TerraformPlan_1
                            spec:
                              provisionerIdentifier: tf_prov
                              configuration:
                                command: Apply
                                configFiles:
                                  store:
                                    spec:
                                      connectorRef: account.pismojpbartogithubconnector
                                      repoName: harness-eval
                                      gitFetchType: Branch
                                      branch: main
                                      folderPath: terraform
                                    type: Github
                                providerCredential:
                                  type: Aws
                                  spec:
                                    connectorRef: account.pismojpbartoawslocal
                                    region: eu-west-1
                                    roleArn: ""
                                secretManagerRef: account.harnessSecretManager
                                exportTerraformPlanJson: true
                                storeTfPlanOnDelegate: true
                                exportTerraformHumanReadablePlan: true
                                skipRefreshCommand: false
                            timeout: 10m
                  tags: {}
        - insert:
            identifier: Deploy
            stages:
              - stage:
                  name: Prepare to Deploy
                  identifier: Prepare_to_Deploy
                  description: ""
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            type: TerraformApply
                            name: TerraformApply_1
                            identifier: TerraformApply_1
                            spec:
                              provisionerIdentifier: tf_prov
                              configuration:
                                type: InheritFromPlan
                            timeout: 10m
                  tags: {}
        - insert:
            identifier: Validate
            stages:
              - stage:
                  name: Validate Deployment
                  identifier: Validate_Deployment
                  description: ""
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            type: ShellScriptProvision
                            name: ShellScriptProvision_1
                            identifier: ShellScriptProvision_1
                            spec:
                              source:
                                type: Inline
                                spec:
                                  script: |-
                                    echo i will validate the parameter store value
                                    which aws
                              environmentVariables: []
                            timeout: 10m
                  tags: {}
  projectIdentifier: harnessdeployeval
  orgIdentifier: pismo
