pipeline:
  name: pismo-jpbarto-deploy-pipeline
  identifier: pismojpbartodeploypipeline
  tags: {}
  template:
    templateRef: account.pismojpbartodeploytemplate
    versionLabel: v1
    gitBranch: main
    templateInputs:
      stages:
        - insert:
            identifier: Deploy
            stages:
              - stage:
                  name: Prepare to Deploy
                  identifier: Prepare_to_Deploy
                  description: ""
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            type: ShellScript
                            name: ShellScript_1
                            identifier: ShellScript_1
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: echo preparing to deploy
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                  tags: {}
  projectIdentifier: harnessdeployeval
  orgIdentifier: pismo
