pipeline:
  name: harness-eval-deploy
  identifier: harnessevaldeploy
  tags: {}
  template:
    templateRef: jpbartodeploymenttemplate
    versionLabel: v1
    templateInputs:
      stages:
        - insert:
            identifier: Deploy
            stages:
              - stage:
                  name: DeployTF
                  identifier: CustomDeploy
                  description: ""
                  type: Custom
                  spec:
                    execution:
                      steps:
                        - step:
                            type: ShellScript
                            name: ShellScript_1
                            identifier: ShellScript_1
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: echo preparing to install harness eval
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                        - step:
                            type: TerraformApply
                            name: TerraformApply_1
                            identifier: TerraformApply_1
                            spec:
                              provisionerIdentifier: tfprovisionid
                              configuration:
                                type: Inline
                                spec:
                                  configFiles:
                                    store:
                                      spec:
                                        connectorRef: jpbartogithubconn
                                        repoName: harness-eval
                                        gitFetchType: Branch
                                        branch: main
                                        folderPath: terraform
                                      type: Github
                                  providerCredential:
                                    type: Aws
                                    spec:
                                      connectorRef: jpbartoaws
                                      region: eu-west-1
                                      roleArn: ""
                            timeout: 10m
                  outputs:
                    - name: deployTFOutput
                      value: there is value here
                  tags: {}
              - stage:
                  name: DeployK8s
                  identifier: SerialDeployK8s
                  description: ""
                  type: Deployment
                  spec:
                    deploymentType: Kubernetes
                    service:
                      serviceRef: harnessevalguestbook
                      disableArtifactValidation: true
                    environment:
                      environmentRef: jpbartoenv
                      deployToAll: false
                      infrastructureDefinitions:
                        - identifier: jpbartok8sinfra
                    execution:
                      steps:
                        - step:
                            type: ShellScript
                            name: ShellScript_2
                            identifier: ShellScript_2
                            spec:
                              shell: Bash
                              executionTarget: {}
                              source:
                                type: Inline
                                spec:
                                  script: echo see output value as <+pipeline.stages.DeployTF.output.deployTFOutput>
                              environmentVariables: []
                              outputVariables: []
                            timeout: 10m
                        - step:
                            type: K8sApply
                            name: K8sApply_1
                            identifier: K8sApply_1
                            spec:
                              skipDryRun: false
                              skipSteadyStateCheck: false
                              skipRendering: false
                              overrides: []
                              manifestSource:
                                type: K8sManifest
                                spec:
                                  store:
                                    type: Github
                                    spec:
                                      connectorRef: jpbartogithubconn
                                      paths:
                                        - harness-cicd/harnesseval-ns.yaml
                                      gitFetchType: Branch
                                      branch: main
                                      repoName: harness-eval
                            timeout: 10m
                        - step:
                            name: Stage Deployment
                            identifier: stageDeployment
                            type: K8sBlueGreenDeploy
                            timeout: 10m
                            spec:
                              skipDryRun: false
                              pruningEnabled: false
                        - step:
                            name: Swap primary with stage service
                            identifier: bgSwapServices
                            type: K8sBGSwapServices
                            timeout: 10m
                            spec:
                              skipDryRun: false
                      rollbackSteps:
                        - step:
                            name: Swap primary with stage service
                            identifier: rollbackBgSwapServices
                            type: K8sBGSwapServices
                            timeout: 10m
                            spec:
                              skipDryRun: false
                  tags: {}
                  failureStrategies:
                    - onFailure:
                        errors:
                          - AllErrors
                        action:
                          type: StageRollback
  projectIdentifier: harnessdeployeval
  orgIdentifier: pismo
