pipeline:
  name: Build harness-eval
  identifier: Build_harness_eval_1775858987359
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: CloneRepo
                  identifier: CloneRepo
                  spec:
                    connectorRef: account.jpbartogithub
                    repoName: harness-eval
                    build:
                      type: branch
                      spec:
                        branch: main
              - step:
                  type: Run
                  name: Build Helm Chart
                  identifier: Build_Helm_Chart
                  spec:
                    shell: Sh
                    command: helm package helm/guestbook --version '1.0.7'
              - step:
                  type: Run
                  name: Push to TTL
                  identifier: Push_to_TTL
                  spec:
                    shell: Sh
                    command: helm push helm-guestbook-1.0.7.tgz 'oci://ttl.sh/jpbarto/charts/helm-guestbook'
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.jpbartogithub
        repoName: harness-eval
        build: <+input>
